prodajsi/ProdajSI/Models/AdViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProdajSI.Models
{
    public class CategoryListViewModel
    {
        [Required]
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Category")]
        public string Category { get; set; }
    }

    public class AdDetailsViewModel
    {
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Post Date")]
        public DateTime PostDate { get; set; }

        [Required]
        [Display(Name = "Contact")]
        public string Contact { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Price")]
        public double Price { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Category")]
        public string Category { get; set; }

        [Required]
        [Display(Name = "Region")]
        public string Region { get; set; }

        [Required]
        [Display(Name = "Images")]
        public List<string> Images { get; set; }
    }

    public class AdListViewModel
    {
        [Required]
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Price")]
        public double Price { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Image")]
        public string DisplayImage { get; set; }
    }

    public class CreateAdViewModel
    {
        public CreateAdViewModel()
        {
            Images = new List<HttpPostedFileBase>();
        }

        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Contact")]
        public string Contact { get; set; }

        [Required]
        [Range(0.01, Double.MaxValue)]
        [DataType(DataType.Currency)]
        [Display(Name = "Price")]
        public double Price { get; set; }

        [StringLength(500)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int IdCategory { get; set; }

        [Required]
        [Display(Name = "Region")]
        public int IdRegion { get; set; }

        [Display(Name = "Images")]
        public List<HttpPostedFileBase> Images { get; set; }
    }

    public class EditAdViewModel
    {
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Contact")]
        public string Contact { get; set; }

        [Required]
        [Range(0.01, Double.MaxValue)]
        [DataType(DataType.Currency)]
        [Display(Name = "Price")]
        public double Price { get; set; }

        [StringLength(500)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int IdCategory { get; set; }

        [Required]
        [Display(Name = "Region")]
        public int IdRegion { get; set; }
    }
}

prodajsi/ProdajSI/Models/Ads.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdajSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ads()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int id_ad { get; set; }
        public string title { get; set; }
        public System.DateTime post_date { get; set; }
        public string contact { get; set; }
        public double price { get; set; }
        public string description { get; set; }
        public string id_user { get; set; }
        public int id_category { get; set; }
        public int id_region { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Regions Regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}

prodajsi/ProdajSI/Controllers/AdsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProdajSI.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using System.IO;

namespace ProdajSI.Controllers
{
    public class AdsController : Controller
    {
        ProdajEntities db = new ProdajEntities();


        // GET: Ads
        public ActionResult Index()
        {
            ViewBag.Category = "All Categories";

            var categories = new List<CategoryListViewModel>();
            foreach(var category in db.Categories)
            {
                categories.Add(new CategoryListViewModel
                {
                    Id = category.id_category,
                    Category = category.category
                });
            }
            return View(categories);
        }

        // GET: Ads/Search
        public ActionResult Search(int? category, int? page, string title)
        {
            var _ads = db.Ads.AsQueryable();

            ViewBag.Category = "All Categories";
            if (category != null)
            {
                _ads = _ads.Where(a => a.id_category == category);
                ViewBag.Category = db.Categories.Find(category).category;
            }
            
            if (!String.IsNullOrEmpty(title))
                _ads = _ads.Where(a => a.title.ToLower().Contains(title.ToLower()));
            
            var ads = new List<AdListViewModel>();
            foreach (var _ad in _ads)
            {
                ads.Add(new AdListViewModel
                {
                    Id = _ad.id_ad,
                    Title = _ad.title,
                    Price = _ad.price,
                    Description = _ad.description,
                    DisplayImage = _ad.Images.Count() > 0 ? String.Format("~/Images/{0}/{1}", _ad.id_ad, _ad.Images.First().url) : "~/Images/placeholder.png"
                });
            }

            int pageSize = 10;
                        
            /*if (!Int32.TryParse(Request.QueryString["page"], out page))
                page = 1;*/

            if (page > Math.Ceiling((decimal)_ads.Count() / pageSize))
                page = 1;

            var ads_paged = ads.ToPagedList(page ?? 1, pageSize);
            return View(ads_paged);
        }

        // GET: Ads/Details/5
        public ActionResult Details(int id)
        {
            var _ad = db.Ads.Find(id);
            if (_ad == null)
                Redirect("Error");

            var Images = new List<string>();
            foreach(var img in _ad.Images)
            {
                Images.Add(String.Format("~/Images/{0}/{1}", _ad.id_ad, img.url));
            }

            var ad = new AdDetailsViewModel
            {
                Title = _ad.title,
                PostDate = _ad.post_date,
                Contact = _ad.contact,
                Price = _ad.price,
                Description = _ad.description,
                Category = _ad.Categories.category,
                Region = _ad.Regions.region,
                Images = Images
            };
            return View(ad);
        }

        // GET: Ads/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Category = new SelectList(db.Categories, "id_category", "category");
            ViewBag.Region = new SelectList(db.Regions, "id_region", "region");

            return View();
        }

        // POST: Ads/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateAdViewModel ad)
        {
            ViewBag.Category = new SelectList(db.Categories, "id_category", "category");
            ViewBag.Region = new SelectList(db.Regions, "id_region", "region");

            if (!ModelState.IsValid)
            {
                return View(ad);
            }

            var _ad = new Ads
            {
                title = ad.Title,
                post_date = DateTime.Now,
                contact = ad.Contact,
                price = ad.Price,
                description = ad.Description,
                id_user = User.Identity.GetUserId(),
                id_category = ad.IdCategory,
                id_region = ad.IdRegion
            };

            foreach (var image in ad.Images)
            {
                if(image != null)
                {
                    if (String.IsNullOrEmpty(Path.GetExtension(image.FileName)) || (
                        Path.GetExtension(image.FileName) != ".jpg" &&
                        Path.GetExtension(image.FileName) != ".jpeg" &&
                        Path.GetExtension(image.FileName) != ".png"
                        ))
                        return View(ad);
                    var filename = Path.GetFileName(image.FileName);
                    _ad.Images.Add(new Images
                    {
                        url = filename
                    });
                }
            }

            db.Ads.Add(_ad);
            db.SaveChanges();

            
            foreach (var image in ad.Images)
            {
                if(image != null)
                {
                    var filename = Path.GetFileName(image.FileName);
                    if (!Directory.Exists(Server.MapPath("~/Images/" + _ad.id_ad)))
                        Directory.CreateDirectory(Server.MapPath("~/Images/" + _ad.id_ad));
                    var savepath = Path.Combine(Server.MapPath("~/Images/" + _ad.id_ad + "/") + filename);
                    image.SaveAs(savepath);
                }
            }

            return RedirectToAction("Index");
        }

        // GET: Ads/userID
        [Authorize]
        public ActionResult AdsByUser(string user = "")
        {
            var _ads = db.Ads.Where(a => a.id_user.Equals(user));

            var ads = new List<AdListViewModel>();
            foreach (var _ad in _ads)
            {
                ads.Add(new AdListViewModel
                {
                    Id = _ad.id_ad,
                    Title = _ad.title,
                    Price = _ad.price,
                    Description = _ad.description,
                    DisplayImage = _ad.Images.Count() > 0 ? String.Format("~/Images/{0}/{1}", _ad.id_ad, _ad.Images.First().url) : "~/Images/placeholder.png"
                });
            }

            return View(ads);
        }

        // GET: Ads/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var _ad = db.Ads.Find(id);

            if(_ad == null)
                Redirect("NotFound");

            if (_ad.id_user != User.Identity.GetUserId())
                RedirectToAction("Index");

            ViewBag.Category = new SelectList(db.Categories, "id_category", "category");
            ViewBag.Region = new SelectList(db.Regions, "id_region", "region");

            var ad = new EditAdViewModel
            {
                Title = _ad.title,
                Contact = _ad.contact,
                Price = _ad.price,
                Description = _ad.description,
                IdCategory = _ad.id_category,
                IdRegion = _ad.id_region
            };

            return View(ad);
        }

        // POST: Ads/Edit/5
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, EditAdViewModel ad)
        {
            if (!ModelState.IsValid)
            {
                return View(ad);
            }

            var _ad = db.Ads.Find(id);

            if (_ad.id_user != User.Identity.GetUserId())
                RedirectToAction("Index");
            
            ViewBag.Category = new SelectList(db.Categories, "id_category", "category");
            ViewBag.Region = new SelectList(db.Regions, "id_region", "region");

            _ad.title = ad.Title;
            _ad.contact = ad.Contact;
            _ad.price = ad.Price;
            _ad.description = ad.Description;
            _ad.id_category = ad.IdCategory;
            _ad.id_region = ad.IdRegion;
            db.SaveChanges();

            return RedirectToAction("Details", new { id });
        }

        // POST: Ads/Delete/5
        [Authorize]
        [NonAction]
        public ActionResult Delete(int id)
        {
            var _ad = db.Ads.Find(id);

            if (_ad != null)
                db.Ads.Remove(_ad);

            return RedirectToAction("Index");
        }
    }
}

prodajsi/ProdajSI/Views/Ads/AdsByUser.cshtml
@model IEnumerable<ProdajSI.Models.AdListViewModel>

@{
    ViewBag.Title = "AdsByUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="mt-4"></div>
<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Details", new { id = item.Id })">
                        <img src="@Url.Content(item.DisplayImage)" height="50" />
                    </a>
                </td>
                <td>@Html.ActionLink(item.Title, "Details", "Ads", routeValues: new { id = item.Id }, htmlAttributes: new {})</td>
                <td>@Html.DisplayFor(modeltem => item.Price)</td>
                <td>@Html.ActionLink("Edit", "Edit", "Ads", routeValues: new { id = item.Id }, htmlAttributes: new {})</td>
            </tr>
        }

    </tbody>
</table>

prodajsi/ProdajSI/Views/Ads/Category.cshtml
@model IEnumerable<ProdajSI.Models.AdListViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
    </tr>
}

</table>

prodajsi/ProdajSI/Views/Ads/Create.cshtml
@model ProdajSI.Models.CreateAdViewModel

@{
    ViewBag.Title = "Post Ad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="mt-4 text-center">Post Ad</h3>

@using (Html.BeginForm("Create", "Ads", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Title</div>
                </div>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Contact</div>
                </div>
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Price</div>
                </div>
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", @rows = "5", @placeholder = "Description" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Title</div>
                </div>
                @Html.DropDownListFor(model => model.IdCategory, ViewBag.Category as IEnumerable<SelectListItem>, "Category", htmlAttributes: new { @class = "form-control" })
            </div>
            @Html.ValidationMessageFor(model => model.IdCategory, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Title</div>
                </div>
                @Html.DropDownListFor(model => model.IdRegion, ViewBag.Region as IEnumerable<SelectListItem>, "Region", htmlAttributes: new { @class = "form-control" })
            </div>
            @Html.ValidationMessageFor(model => model.IdRegion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Images</div>
                </div>
                <div class="custom-file">
                    @Html.TextBoxFor(model => model.Images, new { @type = "file", @multiple = "multiple", @accept = ".jpg,.png,.jpeg" })
                    <label id="ImagesLabel" class="custom-file-label" for="Images">Choose files</label>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2 text-center">
            <button type="submit" class="btn btn-outline-primary">Create</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $("#Images").change(function () {
            document.getElementById("ImagesLabel").innerText = document.getElementById("Images").files.length + " files selected";
        })
    </script>
}

prodajsi/ProdajSI/Views/Ads/Details.cshtml
@model ProdajSI.Models.AdDetailsViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row mt-4">
    <div class="offset-2 col-md-8">
        <h4 class="d-inline-block">@Html.DisplayFor(model => model.Title)</h4>
        <h4 class="float-right text-danger">@Html.DisplayFor(model => model.Price)</h4>
    </div>
</div>

<div class="row mt-4">
    <div class="offset-2 col-md-8">
        <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="false" style="height: 402px; border: 1px solid; border-color: rgba(0,0,0,0.15)">
            <ol class="carousel-indicators">
                @{
                    for (var i = 0; i < Model.Images.Count(); i++)
                    {
                        <li data-target="#carousel" data-slide-to="@i"></li>
                    }
                }
            </ol>
            <div class="carousel-inner">
                @{
                    foreach (var url in Model.Images)
                    {
                        <div class="carousel-item">
                            <img src="@Url.Content(url)" class="d-block" style="width: auto; height: 400px; margin: auto;" />
                        </div>
                    }
                }
            </div>
            <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="offset-2 col-md-8">
        <table class="table table-borderless">
            <tr>
                <th scope="row" class="text-right" style="width: 1px">@Html.DisplayNameFor(model => model.Category)</th>
                <td>@Html.DisplayFor(model => model.Category)</td>
            </tr>
            <tr>
                <th scope="row" class="text-right" style="width: 1px">@Html.DisplayNameFor(model => model.Region)</th>
                <td>@Html.DisplayFor(model => model.Region)</td>
            </tr>
            <tr>
                <th scope="row" class="text-right" style="width: 1px">@Html.DisplayNameFor(model => model.PostDate)</th>
                <td>@Html.DisplayFor(model => model.PostDate)</td>
            </tr>
            <tr>
                <th scope="row" class="text-right" style="width: 1px">@Html.DisplayNameFor(model => model.Contact)</th>
                <td>@Html.DisplayFor(model => model.Contact)</td>
            </tr>
            <tr>
                <th scope="row" class="text-right" style="width: 1px">@Html.DisplayNameFor(model => model.Description)</th>
                <td>@Html.DisplayFor(model => model.Description)</td>
            </tr>
        </table>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        document.getElementById("carousel").children[0].firstElementChild.classList.add("active");
        document.getElementById("carousel").children[1].firstElementChild.classList.add("active");
    </script>
}

prodajsi/ProdajSI/Views/Ads/Edit.cshtml
@model ProdajSI.Models.EditAdViewModel
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="mt-4 text-center">Edit Ad</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Title</div>
                </div>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Contact</div>
                </div>
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Price</div>
                </div>
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", @rows = "5", @placeholder = "Description" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Title</div>
                </div>
                @Html.DropDownListFor(model => model.IdCategory, ViewBag.Category as IEnumerable<SelectListItem>, "Category", htmlAttributes: new { @class = "form-control" })
            </div>
            @Html.ValidationMessageFor(model => model.IdCategory, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">Title</div>
                </div>
                @Html.DropDownListFor(model => model.IdRegion, ViewBag.Region as IEnumerable<SelectListItem>, "Region", htmlAttributes: new { @class = "form-control" })
            </div>
            @Html.ValidationMessageFor(model => model.IdRegion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-8 offset-2 text-center">
            @Html.ActionLink("Cancel", "AdsByUser", "Ads", routeValues: new { user = User.Identity.GetUserId() }, htmlAttributes: new { @class = "btn btn-outline-danger" })
            <button type="submit" class="btn btn-outline-success">Confirm</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prodajsi/ProdajSI/Views/Ads/Index.cshtml
@model IEnumerable<ProdajSI.Models.CategoryListViewModel>

@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("search", "ads", method: FormMethod.Get))
{
    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">@ViewBag.Category</span>
                </div>
                <input hidden name="page" value="1" />
                <input name="title" type="search" class="form-control" placeholder="Search" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-success">Search</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="row mt-4">
    <div class="col-md-8 offset-2">
        <div class="row">
            @{
                foreach (var category in Model)
                {
                    <div class="col-md-3">
                        @Html.ActionLink(category.Category, "search", new { category = category.Id }, htmlAttributes: new { @class = "btn btn-block btn-outline-dark mt-2" })
                    </div>
                }
            }
        </div>
    </div>
</div>

prodajsi/ProdajSI/Views/Ads/Search.cshtml
@model PagedList.IPagedList<ProdajSI.Models.AdListViewModel>
@using PagedList.Mvc;

@{
    ViewBag.Title = ViewBag.Category;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("search", "ads", method: FormMethod.Get))
{
    <div class="row mt-4">
        <div class="col-md-8 offset-2">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">@ViewBag.Category</span>
                </div>
                @if (!Request.QueryString["category"].IsEmpty())
                {
                    <input hidden name="category" type="text" value="@Request.QueryString["category"]" />
                }
                <input hidden name="page" type="text" value="1" />
                <input name="title" type="search" class="form-control" placeholder="Search" value="@Request.QueryString["title"]" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-success">Search</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="mt-4"></div>
@foreach (var item in Model)
{
    <hr />
    <div class="row">
        <div class="col-md-2">
            <a href="@Url.Action("Details", new { id = item.Id })">
                <img src="@Url.Content(item.DisplayImage)" class="display-image" />
            </a>
        </div>
        <div class="col-md-10">
            <h3 class="d-inline">@Html.ActionLink(item.Title, "Details", new { id = item.Id })</h3>
            <h4 class="float-right">@Html.DisplayFor(modelItem => item.Price)</h4>
            <p>@item.Description</p>
        </div>
    </div>
}

<br />
@Html.PagedListPager(Model, page => Url.Action("search", new { category = Request.QueryString["category"], page, title = Request.QueryString["title"] }), new PagedListRenderOptions {
    LiElementClasses = new List<String> { "page-item" },
    UlElementClasses = new[] { "pagination justify-content-center" }
})

@section Scripts
{
    <script type="text/javascript">
        $(".page-item a").addClass("page-link");
    </script>
}